import React from "react";
import Link from "next/link";
import styles from "./TermsAndConditions.module.css";

const TermsAndConditions = () => {
  return (
    <main className={styles.termsPage}>
      {/* Hero Section */}
      <section className={styles.hero}>
        <div className={styles.heroGlow}></div>

        <div className={styles.heroContent}>
          <p className={styles.breadcrumb}>
            <Link href="/">Home</Link>
            <span> / </span>
            Terms and Conditions
          </p>

          <div className={styles.badge}>YANKA Legal</div>

          <h1>Terms and Conditions</h1>

          <p className={styles.heroText}>
            These Terms and Conditions govern your access to and use of YANKA,
            including our platform, AI tools, content marketplace, and related
            services. By using YANKA, you agree to these terms.
          </p>

          <div className={styles.metaRow}>
            <span>Effective Date: February 23, 2026</span>
            <span>Version 2.0</span>
          </div>
        </div>
      </section>

      {/* Content */}
      <section className={styles.contentSection}>
        <aside className={styles.sidebar}>
          <div className={styles.sidebarCard}>
            <h3>Contents</h3>
            <ul>
              <li><a href="#definitions">1. Definitions</a></li>
              <li><a href="#eligibility">2. Eligibility & Registration</a></li>
              <li><a href="#acceptable-use">3. Acceptable Use Policy</a></li>
              <li><a href="#intellectual-property">4. Intellectual Property</a></li>
              <li><a href="#marketplace">5. Marketplace & Monetization</a></li>
              <li><a href="#ai-tools">6. AI Tools & Avatars</a></li>
              <li><a href="#privacy">7. Privacy & Data Protection</a></li>
              <li><a href="#enterprise">8. Enterprise & Institutional Terms</a></li>
              <li><a href="#liability">9. Warranty Disclaimer & Limitation of Liability</a></li>
              <li><a href="#indemnification">10. Indemnification</a></li>
              <li><a href="#termination">11. Termination</a></li>
              <li><a href="#governing-law">12. Governing Law & Dispute Resolution</a></li>
              <li><a href="#modifications">13. Modifications</a></li>
              <li><a href="#contact">14. Contact</a></li>
            </ul>
          </div>
        </aside>

        <div className={styles.mainContent}>
          <div className={styles.introCard}>
            <p>
              Welcome to <strong>YANKA</strong>. Please read these Terms
              carefully. They contain important information about your rights,
              obligations, acceptable use, and limitations of liability.
            </p>
          </div>

          <section id="definitions" className={styles.card}>
            <h2>1. Definitions</h2>
            <ul>
              <li><strong>Platform:</strong> The YANKA AI application, website, APIs, and all associated services.</li>
              <li><strong>User:</strong> Any individual or entity accessing the Platform.</li>
              <li><strong>Creator:</strong> A User who publishes content on the YANKA Marketplace.</li>
              <li><strong>Learner:</strong> A User who accesses educational content on the Platform.</li>
              <li><strong>Institution:</strong> A school, university, corporation, NGO, or government entity using YANKA.</li>
              <li><strong>User Content:</strong> All content created, uploaded, or generated by Users using YANKA tools.</li>
              <li><strong>AI-Generated Content:</strong> Content produced using YANKA's AI tools based on User inputs.</li>
              <li><strong>Services:</strong> All features, tools, and functionalities offered through the Platform.</li>
            </ul>
          </section>

          <section id="eligibility" className={styles.card}>
            <h2>2. Eligibility & Account Registration</h2>
            <h3>2.1 Eligibility</h3>
            <p>
              You must be at least 13 years old, or the minimum legal age in
              your jurisdiction, to use YANKA. Users under 18 require parental
              or guardian consent.
            </p>

            <h3>2.2 Account Security</h3>
            <p>You are responsible for:</p>
            <ul>
              <li>Maintaining the confidentiality of your login credentials</li>
              <li>All activity that occurs under your account</li>
              <li>Notifying YANKA immediately of any unauthorized access</li>
            </ul>
          </section>

          <section id="acceptable-use" className={styles.card}>
            <h2>3. Acceptable Use Policy</h2>
            <h3>3.1 Permitted Uses</h3>
            <p>
              You may use YANKA to learn, teach, create content, conduct
              research, build professional training, and monetize your expertise
              within the bounds of these Terms.
            </p>

            <h3>3.2 Prohibited Uses</h3>
            <ul>
              <li>Violate any applicable law, regulation, or third-party rights</li>
              <li>Infringe intellectual property rights</li>
              <li>Upload harmful, illegal, obscene, or offensive content</li>
              <li>Impersonate any person, organization, or entity</li>
              <li>Bypass security, payment, or authentication systems</li>
              <li>Scrape, crawl, or harvest data without authorization</li>
              <li>Use AI tools for plagiarism, fraud, or research misconduct</li>
              <li>Distribute malware, spam, or harmful software</li>
            </ul>
          </section>

          <section id="intellectual-property" className={styles.card}>
            <h2>4. Intellectual Property</h2>
            <h3>4.1 YANKA&apos;s Intellectual Property</h3>
            <p>
              YANKA retains all rights to the platform, AI tools, avatar
              technology, templates, branding, and underlying infrastructure.
            </p>

            <h3>4.2 User Content Ownership</h3>
            <p>
              You retain ownership of content you create using YANKA tools. By
              using the platform, you grant YANKA a limited, non-exclusive
              license to host, display, back up, and distribute your content as
              needed to provide services.
            </p>

            <h3>4.3 Third-Party Content</h3>
            <p>
              You are solely responsible for ensuring that any third-party
              materials included in your content are properly authorized or used
              lawfully.
            </p>
          </section>

          <section id="marketplace" className={styles.card}>
            <h2>5. Marketplace & Monetization</h2>
            <h3>5.1 Creator Responsibilities</h3>
            <ul>
              <li>You own or have rights to distribute your content</li>
              <li>Your content does not infringe third-party rights</li>
              <li>Your content meets YANKA quality and community standards</li>
              <li>Your pricing is accurate and non-deceptive</li>
            </ul>

            <h3>5.2 Revenue Sharing</h3>
            <p>
              Creators receive 85% of net sales revenue, while YANKA retains 15%
              as a platform and infrastructure fee.
            </p>

            <h3>5.3 Marketplace Standards</h3>
            <p>
              YANKA reserves the right to remove content that violates these
              Terms, community standards, or applicable law.
            </p>

            <h3>5.4 Refund Policy</h3>
            <p>
              Platform subscription fees are generally non-refundable except
              where required by law. Marketplace purchases may be eligible for
              review within 14 days if materially defective or misrepresented.
            </p>
          </section>

          <section id="ai-tools" className={styles.card}>
            <h2>6. AI Tools & Avatars</h2>
            <h3>6.1 AI-Generated Content Disclaimer</h3>
            <p>
              AI-generated content is provided as-is. While YANKA strives for
              quality and relevance, outputs may contain errors or require human
              review.
            </p>

            <h3>6.2 Avatar Creation & Voice Cloning</h3>
            <ul>
              <li>Explicit user consent is required for voice and likeness capture</li>
              <li>Use must comply with applicable biometric and privacy laws</li>
              <li>No impersonation of real individuals without written consent</li>
            </ul>

            <h3>6.3 Academic Use of AI Tools</h3>
            <p>
              Students and researchers must use YANKA responsibly and in
              accordance with institutional academic integrity policies.
            </p>
          </section>

          <section id="privacy" className={styles.card}>
            <h2>7. Privacy & Data Protection</h2>
            <p>
              Your use of YANKA is also governed by our Privacy Policy. By using
              the platform, you acknowledge that you have read and understood how
              your data may be processed in connection with the Services.
            </p>
          </section>

          <section id="enterprise" className={styles.card}>
            <h2>8. Enterprise & Institutional Terms</h2>
            <p>
              Organizations using YANKA through enterprise agreements may be
              subject to additional contractual terms.
            </p>
            <ul>
              <li>Ensuring users within the organization comply with these Terms</li>
              <li>Obtaining necessary consents for data processing</li>
              <li>Complying with relevant data protection laws</li>
              <li>Managing administrator credentials securely</li>
            </ul>
          </section>

          <section id="liability" className={styles.card}>
            <h2>9. Warranty Disclaimer & Limitation of Liability</h2>
            <h3>9.1 Disclaimer</h3>
            <p>
              All Services are provided on an as-is and as-available basis,
              without warranties of any kind, express or implied.
            </p>

            <h3>9.2 Limitation of Liability</h3>
            <p>
              To the maximum extent permitted by law, YANKA shall not be liable
              for indirect, incidental, special, consequential, or punitive
              damages, including loss of profits, data, or business opportunity.
            </p>
          </section>

          <section id="indemnification" className={styles.card}>
            <h2>10. Indemnification</h2>
            <p>
              You agree to defend, indemnify, and hold harmless YANKA and its
              affiliates, officers, directors, employees, and agents from claims,
              damages, losses, and expenses arising from your content, your use
              of the Services, or your violation of these Terms.
            </p>
          </section>

          <section id="termination" className={styles.card}>
            <h2>11. Termination</h2>
            <h3>11.1 Termination by YANKA</h3>
            <p>
              YANKA may suspend or terminate your account for violations of these
              Terms, non-payment, fraudulent or illegal activity, or legal
              compliance reasons.
            </p>

            <h3>11.2 Effect of Termination</h3>
            <ul>
              <li>Access to the platform and your content may be suspended</li>
              <li>You may have a limited period to export eligible content</li>
              <li>Surviving obligations remain enforceable after termination</li>
            </ul>
          </section>

          <section id="governing-law" className={styles.card}>
            <h2>12. Governing Law & Dispute Resolution</h2>
            <p>
              These Terms are governed by applicable law. Disputes will be
              resolved through good-faith negotiation, followed by mediation, and
              then binding arbitration where necessary.
            </p>
          </section>

          <section id="modifications" className={styles.card}>
            <h2>13. Modifications</h2>
            <p>
              YANKA may update these Terms from time to time. Material changes
              may be communicated through platform notifications or email.
              Continued use after updates constitutes acceptance.
            </p>
          </section>

          <section id="contact" className={styles.card}>
            <h2>14. Contact</h2>
            <ul>
              <li><strong>General:</strong> support@yanka.io</li>
              <li><strong>Legal:</strong> legal@yanka.io</li>
              <li><strong>Privacy:</strong> privacy@yanka.io</li>
              <li><strong>Enterprise:</strong> enterprise@yanka.io</li>
              <li><strong>Website:</strong> www.yanka.io</li>
            </ul>
          </section>
        </div>
      </section>
    </main>
  );
};

export default TermsAndConditions;