"use client";

import React from "react";
import Link from "next/link";
import { useLanguage } from "@/context/LanguageContext";
import styles from "./TermsAndConditions.module.css";

const translations = {
  en: {
    home: "Home",
    breadcrumb: "Terms and Conditions",
    badge: "Yanka AI Legal",
    title: "Terms and Conditions",
    heroText:
      "These Terms and Conditions govern your access to and use of Yanka AI, including our platform, AI tools, content marketplace, and related services. By using Yanka AI, you agree to these terms.",
    effectiveDate: "Effective Date: February 23, 2026",
    version: "Version 2.0",

    contents: "Contents",
    sidebarLinks: {
      definitions: "1. Definitions",
      eligibility: "2. Eligibility & Registration",
      acceptableUse: "3. Acceptable Use Policy",
      intellectualProperty: "4. Intellectual Property",
      marketplace: "5. Marketplace & Monetization",
      aiTools: "6. AI Tools & Avatars",
      privacy: "7. Privacy & Data Protection",
      enterprise: "8. Enterprise & Institutional Terms",
      liability: "9. Warranty Disclaimer & Limitation of Liability",
      indemnification: "10. Indemnification",
      termination: "11. Termination",
      governingLaw: "12. Governing Law & Dispute Resolution",
      modifications: "13. Modifications",
      contact: "14. Contact",
    },

    intro:
      "Welcome to Yanka AI. Please read these Terms carefully. They contain important information about your rights, obligations, acceptable use, and limitations of liability.",

    definitionsTitle: "1. Definitions",
    definitionsBullets: [
      {
        strong: "Platform:",
        text: " The Yanka AI AI application, website, APIs, and all associated services.",
      },
      {
        strong: "User:",
        text: " Any individual or entity accessing the Platform.",
      },
      {
        strong: "Creator:",
        text: " A User who publishes content on the Yanka AI Marketplace.",
      },
      {
        strong: "Learner:",
        text: " A User who accesses educational content on the Platform.",
      },
      {
        strong: "Institution:",
        text: " A school, university, corporation, NGO, or government entity using YANKA.",
      },
      {
        strong: "User Content:",
        text: " All content created, uploaded, or generated by Users using YANKA tools.",
      },
      {
        strong: "AI-Generated Content:",
        text: " Content produced using Yanka's AI tools based on User inputs.",
      },
      {
        strong: "Services:",
        text: " All features, tools, and functionalities offered through the Platform.",
      },
    ],

    eligibilityTitle: "2. Eligibility & Account Registration",
    eligibility21: "2.1 Eligibility",
    eligibility21P:
      "You must be at least 13 years old, or the minimum legal age in your jurisdiction, to use Yanka AI. Users under 18 require parental or guardian consent.",
    eligibility22: "2.2 Account Security",
    eligibility22P: "You are responsible for:",
    eligibility22Bullets: [
      "Maintaining the confidentiality of your login credentials",
      "All activity that occurs under your account",
      "Notifying Yanka AI immediately of any unauthorized access",
    ],

    acceptableUseTitle: "3. Acceptable Use Policy",
    acceptableUse31: "3.1 Permitted Uses",
    acceptableUse31P:
      "You may use Yanka AI to learn, teach, create content, conduct research, build professional training, and monetize your expertise within the bounds of these Terms.",
    acceptableUse32: "3.2 Prohibited Uses",
    acceptableUse32Bullets: [
      "Violate any applicable law, regulation, or third-party rights",
      "Infringe intellectual property rights",
      "Upload harmful, illegal, obscene, or offensive content",
      "Impersonate any person, organization, or entity",
      "Bypass security, payment, or authentication systems",
      "Scrape, crawl, or harvest data without authorization",
      "Use AI tools for plagiarism, fraud, or research misconduct",
      "Distribute malware, spam, or harmful software",
    ],

    intellectualPropertyTitle: "4. Intellectual Property",
    intellectualProperty41: "4.1 Yanka's Intellectual Property",
    intellectualProperty41P:
      "Yanka AI retains all rights to the platform, AI tools, avatar technology, templates, branding, and underlying infrastructure.",
    intellectualProperty42: "4.2 User Content Ownership",
    intellectualProperty42P:
      "You retain ownership of content you create using Yanka AI tools. By using the platform, you grant Yanka AI a limited, non-exclusive license to host, display, back up, and distribute your content as needed to provide services.",
    intellectualProperty43: "4.3 Third-Party Content",
    intellectualProperty43P:
      "You are solely responsible for ensuring that any third-party materials included in your content are properly authorized or used lawfully.",

    marketplaceTitle: "5. Marketplace & Monetization",
    marketplace51: "5.1 Creator Responsibilities",
    marketplace51Bullets: [
      "You own or have rights to distribute your content",
      "Your content does not infringe third-party rights",
      "Your content meets Yanka AI quality and community standards",
      "Your pricing is accurate and non-deceptive",
    ],
    marketplace52: "5.2 Revenue Sharing",
    marketplace52P:
      "Creators receive 85% of net sales revenue, while Yanka AI retains 15% as a platform and infrastructure fee.",
    marketplace53: "5.3 Marketplace Standards",
    marketplace53P:
      "Yanka AI reserves the right to remove content that violates these Terms, community standards, or applicable law.",
    marketplace54: "5.4 Refund Policy",
    marketplace54P:
      "Platform subscription fees are generally non-refundable except where required by law. Marketplace purchases may be eligible for review within 14 days if materially defective or misrepresented.",

    aiToolsTitle: "6. AI Tools & Avatars",
    aiTools61: "6.1 AI-Generated Content Disclaimer",
    aiTools61P:
      "AI-generated content is provided as-is. While Yanka AI strives for quality and relevance, outputs may contain errors or require human review.",
    aiTools62: "6.2 Avatar Creation & Voice Cloning",
    aiTools62Bullets: [
      "Explicit user consent is required for voice and likeness capture",
      "Use must comply with applicable biometric and privacy laws",
      "No impersonation of real individuals without written consent",
    ],
    aiTools63: "6.3 Academic Use of AI Tools",
    aiTools63P:
      "Students and researchers must use Yanka AI responsibly and in accordance with institutional academic integrity policies.",

    privacyTitle: "7. Privacy & Data Protection",
    privacyP:
      "Your use of Yanka AI is also governed by our Privacy Policy. By using the platform, you acknowledge that you have read and understood how your data may be processed in connection with the Services.",

    enterpriseTitle: "8. Enterprise & Institutional Terms",
    enterpriseP:
      "Organizations using Yanka AI through enterprise agreements may be subject to additional contractual terms.",
    enterpriseBullets: [
      "Ensuring users within the organization comply with these Terms",
      "Obtaining necessary consents for data processing",
      "Complying with relevant data protection laws",
      "Managing administrator credentials securely",
    ],

    liabilityTitle: "9. Warranty Disclaimer & Limitation of Liability",
    liability91: "9.1 Disclaimer",
    liability91P:
      "All Services are provided on an as-is and as-available basis, without warranties of any kind, express or implied.",
    liability92: "9.2 Limitation of Liability",
    liability92P:
      "To the maximum extent permitted by law, Yanka AI shall not be liable for indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunity.",

    indemnificationTitle: "10. Indemnification",
    indemnificationP:
      "You agree to defend, indemnify, and hold harmless Yanka AI and its affiliates, officers, directors, employees, and agents from claims, damages, losses, and expenses arising from your content, your use of the Services, or your violation of these Terms.",

    terminationTitle: "11. Termination",
    termination111: "11.1 Termination by Yanka AI",
    termination111P:
      "Yanka AI may suspend or terminate your account for violations of these Terms, non-payment, fraudulent or illegal activity, or legal compliance reasons.",
    termination112: "11.2 Effect of Termination",
    termination112Bullets: [
      "Access to the platform and your content may be suspended",
      "You may have a limited period to export eligible content",
      "Surviving obligations remain enforceable after termination",
    ],

    governingLawTitle: "12. Governing Law & Dispute Resolution",
    governingLawP:
      "These Terms are governed by applicable law. Disputes will be resolved through good-faith negotiation, followed by mediation, and then binding arbitration where necessary.",

    modificationsTitle: "13. Modifications",
    modificationsP:
      "Yanka AI may update these Terms from time to time. Material changes may be communicated through platform notifications or email. Continued use after updates constitutes acceptance.",

    contactTitle: "14. Contact",
    contactBullets: [
      { strong: "General:", text: " support@yanka.io" },
      { strong: "Legal:", text: " legal@yanka.io" },
      { strong: "Privacy:", text: " privacy@yanka.io" },
      { strong: "Enterprise:", text: " enterprise@yanka.io" },
      { strong: "Website:", text: " www.yanka.io" },
    ],
  },

  fr: {
    home: "Accueil",
    breadcrumb: "Conditions générales",
    badge: "Juridique Yanka AI",
    title: "Conditions générales",
    heroText:
      "Les présentes conditions générales régissent votre accès à Yanka AI et votre utilisation de la plateforme, y compris nos outils d’IA, notre marketplace de contenu et les services associés. En utilisant Yanka AI, vous acceptez ces conditions.",
    effectiveDate: "Date d’entrée en vigueur : 23 février 2026",
    version: "Version 2.0",

    contents: "Sommaire",
    sidebarLinks: {
      definitions: "1. Définitions",
      eligibility: "2. Éligibilité et inscription",
      acceptableUse: "3. Politique d’utilisation acceptable",
      intellectualProperty: "4. Propriété intellectuelle",
      marketplace: "5. Marketplace et monétisation",
      aiTools: "6. Outils d’IA et avatars",
      privacy: "7. Confidentialité et protection des données",
      enterprise: "8. Conditions pour entreprises et institutions",
      liability: "9. Exclusion de garantie et limitation de responsabilité",
      indemnification: "10. Indemnisation",
      termination: "11. Résiliation",
      governingLaw: "12. Loi applicable et résolution des litiges",
      modifications: "13. Modifications",
      contact: "14. Contact",
    },

    intro:
      "Bienvenue sur Yanka AI. Veuillez lire attentivement les présentes conditions. Elles contiennent des informations importantes concernant vos droits, obligations, usages autorisés et limitations de responsabilité.",

    definitionsTitle: "1. Définitions",
    definitionsBullets: [
      {
        strong: "Plateforme :",
        text: " l’application Yanka AI, le site web, les API et tous les services associés.",
      },
      {
        strong: "Utilisateur :",
        text: " toute personne physique ou morale accédant à la Plateforme.",
      },
      {
        strong: "Créateur :",
        text: " un Utilisateur qui publie du contenu sur la marketplace Yanka AI.",
      },
      {
        strong: "Apprenant :",
        text: " un Utilisateur qui accède au contenu éducatif sur la Plateforme.",
      },
      {
        strong: "Institution :",
        text: " une école, université, entreprise, ONG ou entité gouvernementale utilisant YANKA.",
      },
      {
        strong: "Contenu utilisateur :",
        text: " tout contenu créé, téléversé ou généré par les Utilisateurs à l’aide des outils YANKA.",
      },
      {
        strong: "Contenu généré par l’IA :",
        text: " contenu produit à l’aide des outils d’IA de Yanka sur la base des entrées de l’Utilisateur.",
      },
      {
        strong: "Services :",
        text: " toutes les fonctionnalités, outils et services proposés via la Plateforme.",
      },
    ],

    eligibilityTitle: "2. Éligibilité et inscription au compte",
    eligibility21: "2.1 Éligibilité",
    eligibility21P:
      "Vous devez avoir au moins 13 ans, ou l’âge légal minimum dans votre juridiction, pour utiliser Yanka AI. Les utilisateurs de moins de 18 ans doivent disposer du consentement d’un parent ou tuteur.",
    eligibility22: "2.2 Sécurité du compte",
    eligibility22P: "Vous êtes responsable de :",
    eligibility22Bullets: [
      "La confidentialité de vos identifiants de connexion",
      "Toute activité se produisant sur votre compte",
      "Informer immédiatement Yanka AI de tout accès non autorisé",
    ],

    acceptableUseTitle: "3. Politique d’utilisation acceptable",
    acceptableUse31: "3.1 Utilisations autorisées",
    acceptableUse31P:
      "Vous pouvez utiliser Yanka AI pour apprendre, enseigner, créer du contenu, mener des recherches, construire des formations professionnelles et monétiser votre expertise dans le respect des présentes Conditions.",
    acceptableUse32: "3.2 Utilisations interdites",
    acceptableUse32Bullets: [
      "Violer toute loi, réglementation ou droits de tiers applicables",
      "Porter atteinte aux droits de propriété intellectuelle",
      "Téléverser du contenu nuisible, illégal, obscène ou offensant",
      "Usurper l’identité d’une personne, organisation ou entité",
      "Contourner les systèmes de sécurité, de paiement ou d’authentification",
      "Extraire, explorer ou collecter des données sans autorisation",
      "Utiliser les outils d’IA pour le plagiat, la fraude ou les fautes en recherche",
      "Distribuer des logiciels malveillants, du spam ou des logiciels nuisibles",
    ],

    intellectualPropertyTitle: "4. Propriété intellectuelle",
    intellectualProperty41: "4.1 Propriété intellectuelle de Yanka",
    intellectualProperty41P:
      "Yanka AI conserve tous les droits sur la plateforme, les outils d’IA, la technologie des avatars, les modèles, l’image de marque et l’infrastructure sous-jacente.",
    intellectualProperty42: "4.2 Propriété du contenu utilisateur",
    intellectualProperty42P:
      "Vous conservez la propriété du contenu que vous créez à l’aide des outils Yanka AI. En utilisant la plateforme, vous accordez à Yanka AI une licence limitée et non exclusive pour héberger, afficher, sauvegarder et distribuer votre contenu dans la mesure nécessaire à la fourniture des services.",
    intellectualProperty43: "4.3 Contenu de tiers",
    intellectualProperty43P:
      "Vous êtes seul responsable de vous assurer que tout contenu tiers inclus dans votre contenu est dûment autorisé ou utilisé légalement.",

    marketplaceTitle: "5. Marketplace et monétisation",
    marketplace51: "5.1 Responsabilités du créateur",
    marketplace51Bullets: [
      "Vous possédez ou détenez les droits de distribution de votre contenu",
      "Votre contenu ne porte pas atteinte aux droits de tiers",
      "Votre contenu respecte les normes de qualité et communautaires de Yanka AI",
      "Votre tarification est exacte et non trompeuse",
    ],
    marketplace52: "5.2 Partage des revenus",
    marketplace52P:
      "Les créateurs reçoivent 85 % du revenu net des ventes, tandis que Yanka AI conserve 15 % en tant que frais de plateforme et d’infrastructure.",
    marketplace53: "5.3 Normes de la marketplace",
    marketplace53P:
      "Yanka AI se réserve le droit de supprimer tout contenu qui enfreint les présentes Conditions, les normes communautaires ou la loi applicable.",
    marketplace54: "5.4 Politique de remboursement",
    marketplace54P:
      "Les frais d’abonnement à la plateforme sont généralement non remboursables sauf lorsque la loi l’exige. Les achats sur la marketplace peuvent faire l’objet d’un examen dans les 14 jours s’ils sont matériellement défectueux ou trompeurs.",

    aiToolsTitle: "6. Outils d’IA et avatars",
    aiTools61: "6.1 Exclusion relative au contenu généré par l’IA",
    aiTools61P:
      "Le contenu généré par l’IA est fourni tel quel. Bien que Yanka AI s’efforce d’assurer la qualité et la pertinence, les résultats peuvent contenir des erreurs ou nécessiter une révision humaine.",
    aiTools62: "6.2 Création d’avatars et clonage vocal",
    aiTools62Bullets: [
      "Le consentement explicite de l’utilisateur est requis pour la capture de la voix et de l’image",
      "L’utilisation doit respecter les lois applicables en matière de biométrie et de vie privée",
      "Aucune imitation de personnes réelles sans consentement écrit",
    ],
    aiTools63: "6.3 Utilisation académique des outils d’IA",
    aiTools63P:
      "Les étudiants et chercheurs doivent utiliser Yanka AI de manière responsable et conformément aux politiques institutionnelles d’intégrité académique.",

    privacyTitle: "7. Confidentialité et protection des données",
    privacyP:
      "Votre utilisation de Yanka AI est également régie par notre Politique de confidentialité. En utilisant la plateforme, vous reconnaissez avoir lu et compris comment vos données peuvent être traitées dans le cadre des Services.",

    enterpriseTitle: "8. Conditions pour entreprises et institutions",
    enterpriseP:
      "Les organisations utilisant Yanka AI dans le cadre de contrats d’entreprise peuvent être soumises à des conditions contractuelles supplémentaires.",
    enterpriseBullets: [
      "Veiller à ce que les utilisateurs au sein de l’organisation respectent les présentes Conditions",
      "Obtenir les consentements nécessaires au traitement des données",
      "Respecter les lois applicables en matière de protection des données",
      "Gérer de manière sécurisée les identifiants administrateur",
    ],

    liabilityTitle: "9. Exclusion de garantie et limitation de responsabilité",
    liability91: "9.1 Exclusion de garantie",
    liability91P:
      "Tous les Services sont fournis tels quels et selon disponibilité, sans garantie d’aucune sorte, expresse ou implicite.",
    liability92: "9.2 Limitation de responsabilité",
    liability92P:
      "Dans toute la mesure permise par la loi, Yanka AI ne pourra être tenu responsable des dommages indirects, accessoires, spéciaux, consécutifs ou punitifs, y compris la perte de profits, de données ou d’opportunités commerciales.",

    indemnificationTitle: "10. Indemnisation",
    indemnificationP:
      "Vous acceptez de défendre, indemniser et dégager de toute responsabilité Yanka AI ainsi que ses affiliés, dirigeants, administrateurs, employés et agents contre toute réclamation, dommage, perte ou dépense résultant de votre contenu, de votre utilisation des Services ou de votre violation des présentes Conditions.",

    terminationTitle: "11. Résiliation",
    termination111: "11.1 Résiliation par Yanka AI",
    termination111P:
      "Yanka AI peut suspendre ou résilier votre compte en cas de violation des présentes Conditions, de non-paiement, d’activité frauduleuse ou illégale, ou pour des raisons de conformité légale.",
    termination112: "11.2 Effets de la résiliation",
    termination112Bullets: [
      "L’accès à la plateforme et à votre contenu peut être suspendu",
      "Vous pouvez disposer d’une période limitée pour exporter le contenu éligible",
      "Les obligations survivantes restent applicables après la résiliation",
    ],

    governingLawTitle: "12. Loi applicable et résolution des litiges",
    governingLawP:
      "Les présentes Conditions sont régies par la loi applicable. Les litiges seront résolus par une négociation de bonne foi, suivie d’une médiation, puis, si nécessaire, d’un arbitrage contraignant.",

    modificationsTitle: "13. Modifications",
    modificationsP:
      "Yanka AI peut mettre à jour les présentes Conditions de temps à autre. Les modifications importantes peuvent être communiquées par notifications sur la plateforme ou par e-mail. La poursuite de l’utilisation après les mises à jour constitue une acceptation.",

    contactTitle: "14. Contact",
    contactBullets: [
      { strong: "Général :", text: " support@yanka.io" },
      { strong: "Juridique :", text: " legal@yanka.io" },
      { strong: "Confidentialité :", text: " privacy@yanka.io" },
      { strong: "Entreprise :", text: " enterprise@yanka.io" },
      { strong: "Site web :", text: " www.yanka.io" },
    ],
  },
};

const TermsAndConditions = () => {
  const { language } = useLanguage();
  const t = translations[language];

  return (
    <main className={styles.termsPage}>
      {/* Hero Section */}
      <section className={styles.hero}>
        <div className={styles.heroGlow}></div>

        <div className={styles.heroContent}>
          <p className={styles.breadcrumb}>
            <Link href="/">{t.home}</Link>
            <span> / </span>
            {t.breadcrumb}
          </p>

          <div className={styles.badge}>{t.badge}</div>

          <h1>{t.title}</h1>

          <p className={styles.heroText}>{t.heroText}</p>

          <div className={styles.metaRow}>
            <span>{t.effectiveDate}</span>
            <span>{t.version}</span>
          </div>
        </div>
      </section>

      {/* Content */}
      <section className={styles.contentSection}>
        <aside className={styles.sidebar}>
          <div className={styles.sidebarCard}>
            <h3>{t.contents}</h3>
            <ul>
              <li><a href="#definitions">{t.sidebarLinks.definitions}</a></li>
              <li><a href="#eligibility">{t.sidebarLinks.eligibility}</a></li>
              <li><a href="#acceptable-use">{t.sidebarLinks.acceptableUse}</a></li>
              <li><a href="#intellectual-property">{t.sidebarLinks.intellectualProperty}</a></li>
              <li><a href="#marketplace">{t.sidebarLinks.marketplace}</a></li>
              <li><a href="#ai-tools">{t.sidebarLinks.aiTools}</a></li>
              <li><a href="#privacy">{t.sidebarLinks.privacy}</a></li>
              <li><a href="#enterprise">{t.sidebarLinks.enterprise}</a></li>
              <li><a href="#liability">{t.sidebarLinks.liability}</a></li>
              <li><a href="#indemnification">{t.sidebarLinks.indemnification}</a></li>
              <li><a href="#termination">{t.sidebarLinks.termination}</a></li>
              <li><a href="#governing-law">{t.sidebarLinks.governingLaw}</a></li>
              <li><a href="#modifications">{t.sidebarLinks.modifications}</a></li>
              <li><a href="#contact">{t.sidebarLinks.contact}</a></li>
            </ul>
          </div>
        </aside>

        <div className={styles.mainContent}>
          <div className={styles.introCard}>
            <p>
              {language === "en" ? (
                <>
                  Welcome to <strong>Yanka AI</strong>. Please read these Terms
                  carefully. They contain important information about your rights,
                  obligations, acceptable use, and limitations of liability.
                </>
              ) : (
                <>
                  Bienvenue sur <strong>Yanka AI</strong>. Veuillez lire attentivement
                  les présentes Conditions. Elles contiennent des informations
                  importantes concernant vos droits, obligations, usages autorisés
                  et limitations de responsabilité.
                </>
              )}
            </p>
          </div>

          <section id="definitions" className={styles.card}>
            <h2>{t.definitionsTitle}</h2>
            <ul>
              {t.definitionsBullets.map((item, index) => (
                <li key={index}>
                  <strong>{item.strong}</strong>
                  {item.text}
                </li>
              ))}
            </ul>
          </section>

          <section id="eligibility" className={styles.card}>
            <h2>{t.eligibilityTitle}</h2>
            <h3>{t.eligibility21}</h3>
            <p>{t.eligibility21P}</p>

            <h3>{t.eligibility22}</h3>
            <p>{t.eligibility22P}</p>
            <ul>
              {t.eligibility22Bullets.map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </section>

          <section id="acceptable-use" className={styles.card}>
            <h2>{t.acceptableUseTitle}</h2>
            <h3>{t.acceptableUse31}</h3>
            <p>{t.acceptableUse31P}</p>

            <h3>{t.acceptableUse32}</h3>
            <ul>
              {t.acceptableUse32Bullets.map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </section>

          <section id="intellectual-property" className={styles.card}>
            <h2>{t.intellectualPropertyTitle}</h2>
            <h3>{t.intellectualProperty41}</h3>
            <p>{t.intellectualProperty41P}</p>

            <h3>{t.intellectualProperty42}</h3>
            <p>{t.intellectualProperty42P}</p>

            <h3>{t.intellectualProperty43}</h3>
            <p>{t.intellectualProperty43P}</p>
          </section>

          <section id="marketplace" className={styles.card}>
            <h2>{t.marketplaceTitle}</h2>
            <h3>{t.marketplace51}</h3>
            <ul>
              {t.marketplace51Bullets.map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>

            <h3>{t.marketplace52}</h3>
            <p>{t.marketplace52P}</p>

            <h3>{t.marketplace53}</h3>
            <p>{t.marketplace53P}</p>

            <h3>{t.marketplace54}</h3>
            <p>{t.marketplace54P}</p>
          </section>

          <section id="ai-tools" className={styles.card}>
            <h2>{t.aiToolsTitle}</h2>
            <h3>{t.aiTools61}</h3>
            <p>{t.aiTools61P}</p>

            <h3>{t.aiTools62}</h3>
            <ul>
              {t.aiTools62Bullets.map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>

            <h3>{t.aiTools63}</h3>
            <p>{t.aiTools63P}</p>
          </section>

          <section id="privacy" className={styles.card}>
            <h2>{t.privacyTitle}</h2>
            <p>{t.privacyP}</p>
          </section>

          <section id="enterprise" className={styles.card}>
            <h2>{t.enterpriseTitle}</h2>
            <p>{t.enterpriseP}</p>
            <ul>
              {t.enterpriseBullets.map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </section>

          <section id="liability" className={styles.card}>
            <h2>{t.liabilityTitle}</h2>
            <h3>{t.liability91}</h3>
            <p>{t.liability91P}</p>

            <h3>{t.liability92}</h3>
            <p>{t.liability92P}</p>
          </section>

          <section id="indemnification" className={styles.card}>
            <h2>{t.indemnificationTitle}</h2>
            <p>{t.indemnificationP}</p>
          </section>

          <section id="termination" className={styles.card}>
            <h2>{t.terminationTitle}</h2>
            <h3>{t.termination111}</h3>
            <p>{t.termination111P}</p>

            <h3>{t.termination112}</h3>
            <ul>
              {t.termination112Bullets.map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </section>

          <section id="governing-law" className={styles.card}>
            <h2>{t.governingLawTitle}</h2>
            <p>{t.governingLawP}</p>
          </section>

          <section id="modifications" className={styles.card}>
            <h2>{t.modificationsTitle}</h2>
            <p>{t.modificationsP}</p>
          </section>

          <section id="contact" className={styles.card}>
            <h2>{t.contactTitle}</h2>
            <ul>
              {t.contactBullets.map((item, index) => (
                <li key={index}>
                  <strong>{item.strong}</strong>
                  {item.text}
                </li>
              ))}
            </ul>
          </section>
        </div>
      </section>
    </main>
  );
};

export default TermsAndConditions;